# Jira Data Center — Packaging Configuration
HELM_REPO_NAME="atlassian-data-center"
HELM_REPO_URL="https://atlassian.github.io/data-center-helm-charts"
HELM_CHART_NAME="jira"
HELM_CHART_REF="atlassian-data-center/jira"
HELM_CHART_VERSION="2.0.12"
HELM_RELEASE_NAME="jira"
IMAGE_REGISTRY=""
HELM_SET_FLAGS=(
  "--set ingress.create=false"
)